blank_issues_enabled: false
contact_links:
  - name: Join4Join Community (Discord)
    url: https://discord.gg/join4join
    about: Please ask and answer general questions that are not bugs or features request)
